Repository apache/skywalking-infra-e2e, pull requests merged in 2021-08, with the labels that each got.

#27 Improve features for verify
  commands/verify/verify.go
  internal/components/verifier/verifier_test.go
  third-party/go/template/exec.go
Labels: enhancement

#28 Fix http trigger could not be schedule by interval
  internal/components/trigger/http.go
Labels: bug

#29 Update GHA `skywalking-cli` commit id
  action.yaml
Labels: dependencies

#30 Some enhancements
  commands/run/run.go
  commands/verify/verify.go
  internal/util/utils.go
Labels: bug, enhancement

#33 Export service host to the environment
  internal/components/setup/compose.go
Labels: chore

#32 Add Dockerfile and use Docker image in GHA
  .github/workflows/build.yaml
  Dockerfile
  Makefile
  action.yaml
Labels: chore

#34 Fix wrong path of Docker entrypoint
  Dockerfile
Labels: chore

#35 Fix wrong GHA volume bind
  action.yaml
Labels: chore

#36 Fix the GHA docker compose wait strategy failure
  internal/components/setup/compose.go
  internal/components/setup/compose_provider.go
Labels: bug

#38 Fix wrong path of Docker GHA
  docker/action.yaml
Labels: bug

#39 Reduce GHA E2E start up time
  Dockerfile
  docker/action.yaml
Labels: enhancement
