Repository apache/skywalking-infra-e2e, pull requests merged in 2021-09, with the labels that each got.

#40 Add official documentation
  README.md
  docs/README.md
  docs/en/concepts-and-designs/README.md
  docs/en/concepts-and-designs/module-design.md
  docs/en/concepts-and-designs/project-goals.md
  docs/en/guide/Compiling-Guidance.md
  docs/en/guide/README.md
  docs/en/guide/setup/Configuration-File.md
  docs/en/guide/setup/Run-E2E-Tests.md
  docs/menu.yml
Labels: documentation

#41 Polishing documentations
  docs/README.md
  docs/en/contribution/Compiling-Guidance.md
  docs/en/contribution/README.md
  docs/en/guide/README.md
  docs/en/setup/Configuration-File.md
  docs/en/setup/README.md
  docs/en/setup/Run-E2E-Tests.md
  docs/menu.yml
Labels: documentation

#43 Add changes and release guide documentations before release
  CHANGES.md
  docs/en/contribution/README.md
  docs/en/contribution/Release-Guidance.md
Labels: chore

#44 refine project-goals.md
  docs/en/concepts-and-designs/project-goals.md
Labels: chore

#45 Add Official documentation link
  README.md
  docs/en/contribution/Release-Guidance.md
Labels: documentation

#46 Added description about the error message in verify
  docs/en/setup/Configuration-File.md
  internal/components/verifier/verifier.go
Labels: documentation

#47 Support profile to export environments
  docs/en/setup/Configuration-File.md
  examples/compose/base-compose.yml
  examples/compose/e2e.yaml
  examples/compose/env
  internal/components/setup/compose.go
  internal/config/e2eConfig.go
  internal/util/utils.go
Labels: enhancement
