Repository apache/skywalking-infra-e2e, pull requests merged in 2021-02, with the labels that each got.

#5 [Setup] create and cleanup k8s cluster config file in tempdir
  internal/components/cleanup/kind.go
  internal/components/setup/kind.go
  internal/constant/kind.go
  internal/util/utils.go
Labels: enhancement

#6 Add precheck for docker daemon in root command
  LICENSE
  commands/root.go
  dist/LICENSE
  go.mod
  go.sum
  internal/util/docker.go
Labels: enhancement

#8 Upgrade license-eye to fix the reviewing bug
  .github/workflows/build.yaml
Labels: chore

#4 Add http action to trigger command
  commands/trigger/action.go
  commands/trigger/http.go
  commands/trigger/trigger.go
  internal/constant/trigget.go
  internal/flags/trigger.go
Labels: feature

#7 Implement the verification of the actual data file
  .golangci.yml
  .licenserc.yaml
  LICENSE
  Makefile
  commands/root.go
  commands/setup/setup.go
  commands/verify/verify.go
  dist/LICENSE
  dist/licenses/LICENSE-go-cmp.txt
  dist/licenses/LICENSE-golang.txt
  go.mod
  internal/components/verifier/funcs.go
  internal/components/verifier/verifier.go
  internal/config/e2eConfig.go
  internal/config/globalConfig.go
  internal/util/utils.go
  test/verify/1.actual.yaml
  test/verify/1.expected.yaml
  third-party/go/internal/fmtsort/sort.go
  third-party/go/template/exec.go
  third-party/go/template/funcs.go
  third-party/go/template/helper.go
  third-party/go/template/option.go
  third-party/go/template/parse/lex.go
  third-party/go/template/parse/node.go
  third-party/go/template/parse/parse.go
  third-party/go/template/template.go
Labels: feature
