Repository apache/skywalking-infra-e2e, pull requests merged in 2021-11, with the labels that each got.

#62 Support save pod/container std log on the Environment
  action.yaml
  commands/root.go
  commands/setup/setup.go
  docs/en/setup/Configuration-File.md
  docs/en/setup/Run-E2E-Tests.md
  internal/components/setup/common.go
  internal/components/setup/compose.go
  internal/components/setup/compose_listener.go
  internal/components/setup/kind.go
  internal/components/setup/kind_listener.go
  internal/util/config.go
  internal/util/env_log.go
  internal/util/k8s.go
  internal/util/restClientGetter.go
Labels: enhancement

#65 Add changes for 1.1.0 version
  CHANGES.md
  Makefile
  changes/changes-1.0.0.md
Labels: chore

#66 Fix the problem of paring verify.retry.interval without setting value
  commands/verify/verify.go
  commands/verify/verify_test.go
Labels: bug

#67 Expand kind file path with system environment
  internal/config/e2eConfig.go
  internal/config/e2eConfig_test.go
Labels: enhancement, feature

#68 Archive v1.1.0 changes
  CHANGES.md
  changes/changes-1.1.0.md
Labels: chore
