Repository apache/skywalking-infra-e2e, pull requests merged in 2022-04, with the labels that each got.

#72 Support installing via `go install` and add install doc
  .gitignore
  Makefile
  cmd/e2e/main.go
  docs/en/setup/Install.md
  docs/en/setup/README.md
  docs/menu.yml
  internal/components/cleanup/kind.go
  internal/components/verifier/funcs.go
  internal/config/globalConfig.go
  internal/util/k8s.go
  internal/util/utils.go
Labels: enhancement

#73 Update Install.md
  docs/en/setup/Install.md
Labels: documentation, chore

#74 Add retry when delete kind cluster
  internal/components/cleanup/kind.go
Labels: enhancement

#75 Fix parsing error
  internal/components/verifier/funcs.go
Labels: bug
