Repository apache/skywalking-infra-e2e, pull requests merged in 2022-11, with the labels that each got.

#91 Remove invalid configuration in GitHub Actions
  action.yaml
Labels: bug

#87 Add .exe suffix to windows build artifact
  Makefile
Labels: chore

#92 Add `batchOutput` config to reduce outputs
  commands/root.go
  commands/verify/verify.go
  internal/util/config.go
  pkg/output/printer.go
Labels: enhancement

#93 Disable batch mode by default, add it to GHA and enable by default
  action.yaml
  commands/root.go
Labels: enhancement
