Repository apache/skywalking-infra-e2e, pull requests merged in 2022-07, with the labels that each got.

#77 upgrade to go1.18
  .github/workflows/build.yaml
  .golangci.yml
  Dockerfile
  Makefile
  commands/verify/verify.go
  commands/verify/verify_test.go
  go.mod
  internal/components/setup/compose.go
  internal/components/verifier/funcs.go
  internal/components/verifier/verifier.go
  internal/config/e2eConfig.go
  third-party/go/template/exec.go
  third-party/go/template/funcs.go
  third-party/go/template/funcs_test.go
  third-party/go/template/parse/lex.go
  third-party/go/template/parse/parse.go
Labels: dependencies

#78 Prepare for release 1.2.0
  CHANGES.md
Labels: documentation

#80 Support `SHA256` and `SHA512` in verify case
  CHANGES.md
  changes/changes-1.2.0.md
  docs/en/setup/Configuration-File.md
  internal/components/verifier/funcs.go
Labels: enhancement

#79 Support non-fail-fast execution of test cases
  commands/verify/verify.go
  docs/en/setup/Configuration-File.md
  examples/compose/e2e.yaml
  go.mod
  go.sum
  internal/config/e2eConfig.go
  internal/config/globalConfig.go
Labels: enhancement
